server:
  port: 8001

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/his?useUnicode=true&characterEncoding=utf8mb4&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
  application:
    name: his-system
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    database: 0
    jedis:
      pool:
        max-active: -8
        max-idle: 300
        max-wait: 5000
        min-idle: 5
    host: 132.232.89.144
    port: 6379
    password: sdzy@123
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/xml/*.xml
